project:
  type: book

book:
  title: |
    Code and data for "HybridExpress: an R/Bioconductor package for comparative transcriptomic analyses of hybrids and their progenitors"
  author: 
    - name: Fabricio Almeida-Silva
      orcid: 0000-0002-5314-2964
  date: "year"
  chapters:
    - index.qmd
    - chapters/chapter_01.qmd
    - chapters/chapter_02.qmd
    - chapters/appendices.qmd

bibliography: bibliography.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo

editor: 
  mode: source